# Generated by Django 3.1.7 on 2021-09-10 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunidade', '0002_auto_20210831_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ofertante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Nome do Dizimista')),
                ('comunidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunidade', to='comunidade.comunidade', verbose_name='Comunidade')),
            ],
            options={
                'verbose_name': 'Dizimista',
                'verbose_name_plural': 'Dizimistas',
                'ordering': ['name'],
            },
        ),
    ]
