# Generated by Django 3.1.7 on 2021-08-31 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paroquia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Nome da Comunidade')),
                ('paroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paroquia', to='paroquia.paroquia', verbose_name='Paróquia')),
            ],
            options={
                'verbose_name': 'Comunidade',
                'verbose_name_plural': 'Comunidades',
                'ordering': ['name'],
            },
        ),
    ]
