# Generated by Django 3.1.7 on 2021-08-31 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paroquia', '0001_initial'),
        ('comunidade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidade',
            name='paroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paroquia', to='paroquia.paroquia', verbose_name='Paróquia'),
        ),
    ]
