# Generated by Django 3.1.7 on 2021-08-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paroquia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paroquia',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Nome da Paróquia'),
        ),
    ]
